Version 2.0

---
Children:
- Children: []
  Properties: {}
  Base: Subsystems
  Name: Subsystems
- Children: []
  Properties: {}
  Base: OI
  Name: Operator Interface
- Children:
  - Children: []
    Properties:
      Parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Parameters
        validators: null
        value: []
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: None}
      Parameter presets: !!robotbuilder.data.properties.ParameterSetProperty
        default: &id001 []
        name: Parameter presets
        validators: null
        value: *id001
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: true}
    Base: Command
    Name: Autonomous Command
  Properties: {}
  Base: Commands
  Name: Commands
Properties:
  Eclipse Workspace: !!robotbuilder.data.properties.FileProperty {default: 'C:\Users\Thomas_Hoffmann\workspace',
    extension: null, folder: true, name: Eclipse Workspace, validators: null, value: 'C:\Users\Thomas_Hoffmann\workspace'}
  Export Commands: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Export Commands, validators: null, value: true}
  Autonomous command parameters: !!robotbuilder.data.properties.ParametersProperty
    default: []
    name: Autonomous command parameters
    validators: null
    value: []
  Java Package: !!robotbuilder.data.properties.StringProperty {default: org.usfirst.frc0000,
    name: Java Package, validators: null, value: org.usfirst.frc5160}
  Use Default Java Package: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Use Default Java Package, validators: null, value: true}
  Team Number: !!robotbuilder.data.properties.IntegerProperty {default: 0, name: Team Number,
    validators: null, value: 5160}
  Export Subsystems: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Export Subsystems, validators: null, value: true}
  Simulation World File: !!robotbuilder.data.properties.StringProperty {default: /usr/share/frcsim/worlds/GearsBotDemo.world,
    name: Simulation World File, validators: null, value: /usr/share/frcsim/worlds/GearsBotDemo.world}
  Wiring file location: !!robotbuilder.data.properties.FileProperty {default: 'C:\Users\Thomas_Hoffmann\',
    extension: null, folder: true, name: Wiring file location, validators: null, value: 'C:\Users\Thomas_Hoffmann\'}
  Autonomous Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
    name: Autonomous Command, type: Command, validators: null, value: Autonomous Command}
Base: Robot
Name: PrototypeBot
